# Generated by Django 3.1.1 on 2020-09-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(null=True, verbose_name='Company')),
                ('product', models.TextField(null=True, verbose_name='Product')),
                ('parameter', models.TextField(null=True, verbose_name='Paramter')),
                ('values', models.TextField(null=True, verbose_name='Values')),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
